/* قائمة مفاتيح الاتصال الدولية مع الأعلام (رمز تعبيري) والاسم بالعربية والإنجليزية. */
export interface Country { code: string; dial: string; flag: string; name: string; nameAr: string }

export const COUNTRIES: Country[] = [
  { code: 'SA', dial: '+966', flag: '🇸🇦', name: 'Saudi Arabia', nameAr: 'السعودية' },
  { code: 'AE', dial: '+971', flag: '🇦🇪', name: 'United Arab Emirates', nameAr: 'الإمارات' },
  { code: 'KW', dial: '+965', flag: '🇰🇼', name: 'Kuwait', nameAr: 'الكويت' },
  { code: 'QA', dial: '+974', flag: '🇶🇦', name: 'Qatar', nameAr: 'قطر' },
  { code: 'BH', dial: '+973', flag: '🇧🇭', name: 'Bahrain', nameAr: 'البحرين' },
  { code: 'OM', dial: '+968', flag: '🇴🇲', name: 'Oman', nameAr: 'عُمان' },
  { code: 'YE', dial: '+967', flag: '🇾🇪', name: 'Yemen', nameAr: 'اليمن' },
  { code: 'JO', dial: '+962', flag: '🇯🇴', name: 'Jordan', nameAr: 'الأردن' },
  { code: 'LB', dial: '+961', flag: '🇱🇧', name: 'Lebanon', nameAr: 'لبنان' },
  { code: 'SY', dial: '+963', flag: '🇸🇾', name: 'Syria', nameAr: 'سوريا' },
  { code: 'IQ', dial: '+964', flag: '🇮🇶', name: 'Iraq', nameAr: 'العراق' },
  { code: 'PS', dial: '+970', flag: '🇵🇸', name: 'Palestine', nameAr: 'فلسطين' },
  { code: 'EG', dial: '+20', flag: '🇪🇬', name: 'Egypt', nameAr: 'مصر' },
  { code: 'SD', dial: '+249', flag: '🇸🇩', name: 'Sudan', nameAr: 'السودان' },
  { code: 'LY', dial: '+218', flag: '🇱🇾', name: 'Libya', nameAr: 'ليبيا' },
  { code: 'TN', dial: '+216', flag: '🇹🇳', name: 'Tunisia', nameAr: 'تونس' },
  { code: 'DZ', dial: '+213', flag: '🇩🇿', name: 'Algeria', nameAr: 'الجزائر' },
  { code: 'MA', dial: '+212', flag: '🇲🇦', name: 'Morocco', nameAr: 'المغرب' },
  { code: 'MR', dial: '+222', flag: '🇲🇷', name: 'Mauritania', nameAr: 'موريتانيا' },
  { code: 'SO', dial: '+252', flag: '🇸🇴', name: 'Somalia', nameAr: 'الصومال' },
  { code: 'DJ', dial: '+253', flag: '🇩🇯', name: 'Djibouti', nameAr: 'جيبوتي' },
  { code: 'KM', dial: '+269', flag: '🇰🇲', name: 'Comoros', nameAr: 'جزر القمر' },
  { code: 'TR', dial: '+90', flag: '🇹🇷', name: 'Türkiye', nameAr: 'تركيا' },
  { code: 'IR', dial: '+98', flag: '🇮🇷', name: 'Iran', nameAr: 'إيران' },
  { code: 'PK', dial: '+92', flag: '🇵🇰', name: 'Pakistan', nameAr: 'باكستان' },
  { code: 'IN', dial: '+91', flag: '🇮🇳', name: 'India', nameAr: 'الهند' },
  { code: 'BD', dial: '+880', flag: '🇧🇩', name: 'Bangladesh', nameAr: 'بنغلاديش' },
  { code: 'ID', dial: '+62', flag: '🇮🇩', name: 'Indonesia', nameAr: 'إندونيسيا' },
  { code: 'MY', dial: '+60', flag: '🇲🇾', name: 'Malaysia', nameAr: 'ماليزيا' },
  { code: 'AF', dial: '+93', flag: '🇦🇫', name: 'Afghanistan', nameAr: 'أفغانستان' },
  { code: 'US', dial: '+1', flag: '🇺🇸', name: 'United States', nameAr: 'الولايات المتحدة' },
  { code: 'CA', dial: '+1', flag: '🇨🇦', name: 'Canada', nameAr: 'كندا' },
  { code: 'GB', dial: '+44', flag: '🇬🇧', name: 'United Kingdom', nameAr: 'المملكة المتحدة' },
  { code: 'FR', dial: '+33', flag: '🇫🇷', name: 'France', nameAr: 'فرنسا' },
  { code: 'DE', dial: '+49', flag: '🇩🇪', name: 'Germany', nameAr: 'ألمانيا' },
  { code: 'IT', dial: '+39', flag: '🇮🇹', name: 'Italy', nameAr: 'إيطاليا' },
  { code: 'ES', dial: '+34', flag: '🇪🇸', name: 'Spain', nameAr: 'إسبانيا' },
  { code: 'NL', dial: '+31', flag: '🇳🇱', name: 'Netherlands', nameAr: 'هولندا' },
  { code: 'BE', dial: '+32', flag: '🇧🇪', name: 'Belgium', nameAr: 'بلجيكا' },
  { code: 'SE', dial: '+46', flag: '🇸🇪', name: 'Sweden', nameAr: 'السويد' },
  { code: 'NO', dial: '+47', flag: '🇳🇴', name: 'Norway', nameAr: 'النرويج' },
  { code: 'CH', dial: '+41', flag: '🇨🇭', name: 'Switzerland', nameAr: 'سويسرا' },
  { code: 'RU', dial: '+7', flag: '🇷🇺', name: 'Russia', nameAr: 'روسيا' },
  { code: 'CN', dial: '+86', flag: '🇨🇳', name: 'China', nameAr: 'الصين' },
  { code: 'JP', dial: '+81', flag: '🇯🇵', name: 'Japan', nameAr: 'اليابان' },
  { code: 'KR', dial: '+82', flag: '🇰🇷', name: 'South Korea', nameAr: 'كوريا الجنوبية' },
  { code: 'AU', dial: '+61', flag: '🇦🇺', name: 'Australia', nameAr: 'أستراليا' },
  { code: 'BR', dial: '+55', flag: '🇧🇷', name: 'Brazil', nameAr: 'البرازيل' },
  { code: 'ZA', dial: '+27', flag: '🇿🇦', name: 'South Africa', nameAr: 'جنوب أفريقيا' },
  { code: 'NG', dial: '+234', flag: '🇳🇬', name: 'Nigeria', nameAr: 'نيجيريا' },
  { code: 'KE', dial: '+254', flag: '🇰🇪', name: 'Kenya', nameAr: 'كينيا' },
  { code: 'ET', dial: '+251', flag: '🇪🇹', name: 'Ethiopia', nameAr: 'إثيوبيا' },
  { code: 'GH', dial: '+233', flag: '🇬🇭', name: 'Ghana', nameAr: 'غانا' },
  { code: 'SN', dial: '+221', flag: '🇸🇳', name: 'Senegal', nameAr: 'السنغال' },
];
